# Generated by Django 6.0.7 on 2026-07-22 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_date', 'city']},
        ),
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('dining', 'Dining'), ('experience', 'Experience'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
